# Generated by Django 2.1.7 on 2019-03-11 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberSystem',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='core.BaseModel')),
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='name')),
                ('population', models.TextField(verbose_name='population')),
            ],
            bases=('core.basemodel',),
        ),
        migrations.AlterUniqueTogether(
            name='counter',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='counter',
            name='owner',
        ),
    ]
